### PR TITLE
Add pre commit tsc testing

### PR DESCRIPTION
**Pull request by kavimaluskam**
### Description
- Run `yarn run test:type` pre-commit

### QA
- [x] Linux

### CODE REVIEW

**Comment by victor77dev** [comment]
How does this work? Do I need to install `pre-commit` in system?
I couldn't commit with my Windows laptop with this.

**Comment by alexkamcrypto** [comment]
@victor77dev This should work when you've installed pre-commit as a devDependencies (so, run `yarn`) and checking will be down when you try to do a commit.

**Comment by kavimaluskam** [comment]
@victor77dev This should work when you've installed pre-commit as a devDependencies (so, run yarn) and checking will be down when you try to do a commit.

**Comment by victor77dev** [comment]
@kavimaluskam looks like my node somehow crashed. Also, my sublime merge is not pointing to the right git to run the pre-commit. But now I figure out the setting.

However, still a question.
It looks always pass?
Look at 8f1e372, it fails when I run `yarn run test:type`, but I could still commit with the cmd showing me `pre-commit` was checked. Is this expected?

**Comment by kavimaluskam** [comment]
@victor77dev It's strange that on my window Linux / Macbook, commit with failed checking is blocked by pre-commit...
```sh
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `test:type`
pre-commit: hook returned an exit code (2). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

**Comment by kavimaluskam** [comment]
@victor77dev Are you using CLI to the git commit / push? what is your setting?

**Comment by victor77dev** [comment]
> @victor77dev Are you using CLI to the git commit / push? what is your setting?

I'm using Windows, tried with power shell, bash, (sublime merge and vscode UI, which should just point to same thing).
```
git commit -m test
[pre-commit 431df8c] test
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by kavimaluskam** [comment]
Probably some issue related to `git-hooks` on windows, Looking for the library `husky` now.

**Comment by kavimaluskam** [comment]
@victor77dev Looks good on my side, try again with `husky`?

**Comment by victor77dev** [comment]
@kavimaluskam I figured out why it didn't work.

`npm config set ignore-scripts true` and then the scripts like `npm run` are skipped.
https://stackoverflow.com/questions/59016328/npm-run-doesnt-do-anything

**Comment by victor77dev** [comment]
@kavimaluskam I think `pre-commit` itself could already set check only when push/commit.
See https://pre-commit.com/#top_level-default_stages

**Comment by victor77dev** [comment]
As discussed before, we could have 4 stages to set validation.
1. no forced
2. do local
3. must have (github action)
4. must have (CI)

And I said "i think check in push is good enough, because sometimes i just want to commit a intermediate commit and squash later. i don't really want to run the check each time".
But now I noticed that the same argument could be for 2nd step when pushing commit to PR too.
Let say if I have a problem with style or type, where I couldn't solve the issue and want to ask for help, then the easiest thing to do is to push it to remote branch and then send the commit link and ask for help. If we need to pass the test when pushing, then it will make asking for help harder.

@kavimaluskam What do you think?

**Comment by kavimaluskam** [comment]
As discussed, the intention of step 1) and 2) is to enforced basic checking done on user side.
But forced checking my bring inconvenience as you mentioned, we can skip the checking and pass to some post-push checking (like github action / ci / building checking). After all the configuration is all about DX.

So i think we can close this PR and enforced the checking later when enforced CI.

@victor77dev

**Comment by victor77dev** [comment]
Sounds good to me.
You've already put the note in https://github.com/Tremendous-Tiny-Team/ttt-web/issues/16.
Closing the PR.

**Pull request closed without merging**
